version: '3'

services:
  app:
    container_name: app
    build:
      context: ./app
    volumes:
      - type: bind
        source: ./app
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports:
      - 8000:3000
    networks:
      - backend
  
  api:
    container_name: api
    build:
      context: ./api
    volumes:
      - type: bind
        source: ./api
        target: /home/node/app
      - type: volume
        target: /home/node/app/node_modules
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
  db:
    image: postgres:15.1
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend: